steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/doubt-sniper-backend', '.', '-f', 'Dockerfile' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/doubt-sniper-backend' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'run', 'deploy', 'doubt-sniper-backend', '--image', 'gcr.io/$PROJECT_ID/doubt-sniper-backend', '--region', 'asia-northeast1', '--platform', 'managed', '--allow-unauthenticated' ]
  env:
  - 'CLOUDSDK_RUN_REGION=asia-northeast1'