[firebase]
api_key = "AIzaSyA2S9udwa_rfoYY9Q8DazscRqetslzuOSA"
auth_domain = "doubt-sniper.firebaseapp.com"
project_id = "doubt-sniper"
storage_bucket = "doubt-sniper.firebasestorage.app"
messaging_sender_id = "404704694046"
app_id = "1:404704694046:web:8de5da2f0ed6588854030f"
measurement_id = "G-YVQBXTKT3R"